import type { Metadata } from "next";
import AdminShell from "./AdminShell";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      style={{ background: "#FFF6F6" }}
      className={`h-screen antialiased overflow-hidden`}
    >
      <AdminShell>{children}</AdminShell>
    </div>
  );
}
