import type { Metadata } from "next";
import SideBar from "./components/SideBar";
import Navbar from "./components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <div
        style={{ background: "#FFF6F6" }}
        className={`h-[100vh] antialiased`}
      >
        <div className="flex h-[100%]">
          <SideBar />
          <div className="flex flex-col flex-1 overflow-hidden">
          
          {/* Navbar */}
          <Navbar />

          {/* Page Content */}
          <main className="flex-1 text-black overflow-y-auto pr-6 py-4">
            {children}
          </main>

        </div>
        </div>
      </div>

  );
}
